<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-23T02:11:26 IST" name="Default suite" finished-at="2022-07-23T02:11:30 IST" duration-ms="4003">
    <groups>
    </groups>
    <test started-at="2022-07-23T02:11:26 IST" name="Default test" finished-at="2022-07-23T02:11:30 IST" duration-ms="4003">
      <class name="testcase_01.TestCase_LP_01">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:testcase_01.TestCase_LP_01@2e3967ea]" started-at="2022-07-23T02:11:26 IST" name="loadConfig" finished-at="2022-07-23T02:11:26 IST" duration-ms="236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testcase_01.TestCase_LP_01@2e3967ea]" started-at="2022-07-23T02:11:26 IST" name="setup" finished-at="2022-07-23T02:11:30 IST" duration-ms="3939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="openCreate()[pri:0, instance:testcase_01.TestCase_LP_01@2e3967ea]" started-at="2022-07-23T02:11:30 IST" name="openCreate" finished-at="2022-07-23T02:11:30 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openCreate -->
        <test-method is-config="true" signature="AfterSuite()[pri:0, instance:testcase_01.TestCase_LP_01@2e3967ea]" started-at="2022-07-23T02:11:30 IST" name="AfterSuite" finished-at="2022-07-23T02:11:30 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentReports.flush()" because "com.liveproject.utility.ExtentManager.Err" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.flush()" because "com.liveproject.utility.ExtentManager.Err" is null
at com.liveproject.utility.ExtentManager.endReport(ExtentManager.java:33)
at com.liveproject.baseclass.BaseClass.AfterSuite(BaseClass.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- testcase_01.TestCase_LP_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
